on:
  push:
    branches:
      - main
    paths:
      - .asf.yaml
      - .github/workflows/docs.yaml
      - docs/**

name: Deploy DataFusion site

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs sources
        uses: actions/checkout@v3

      - name: Checkout asf-site branch
        uses: actions/checkout@v3
        with:
          ref: asf-site
          path: asf-site

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          set -x
          python3 -m venv venv
          source venv/bin/activate
          pip install -r docs/requirements.txt

      - name: Build docs
        run: |
          set -x
          source venv/bin/activate
          cd docs
          ./build.sh

      - name: Copy & push the generated HTML
        run: |
          set -x
          cd asf-site/
          rsync \
            -a \
            --delete \
            --exclude '/.git/' \
            ../docs/build/html/ \
            ./
          cp ../.asf.yaml .
          touch .nojekyll
          git status --porcelain
          if [ "$(git status --porcelain)" != "" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add --all
            git commit -m 'Publish built docs triggered by ${{ github.sha }}'
            git push || git push --force
          fi

  # Run doc tests
  linux-test-doc:
    name: cargo doctest (amd64)
    needs: [ linux-build-lib ]
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-builder
        with:
          rust-version: stable
      # Note: this does not include dictionary_expressions to reduce codegen
      - name: Run doctests
        run: cargo test --doc --features avro,jit,scheduler,json
      - name: Verify Working Directory Clean
        run: git diff --exit-code
