name: Benchmarks

on:
  pull_request:

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout PR changes
        uses: actions/checkout@v4

      - name: Setup data and generate unique result names
        run: |
          cd benchmarks
          mkdir data
          
          # Setup the TPC-H data set with a scale factor of 10
          ./bench.sh data tpch
          
          # Generate a unique-ish identifier for the results using 
          # branch name and commit sha
          short_ref=$(echo "${{ github.head_ref }}" | cut -c1-20)
          short_sha=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "HEAD_REF_SHA=$short_ref-$short_sha" >> "$GITHUB_ENV" 
          
          short_sha=$(echo "${{ github.event.pull_request.base.sha }}" | cut -c1-7)
          echo "BASE_REF_SHA=${{ github.base_ref }}-$short_sha" >> "$GITHUB_ENV"

      - name: Benchmark PR changes
        env:
          RESULTS_NAME: ${{ env.HEAD_REF_SHA }}
        run: |
          cd benchmarks

          ./bench.sh run tpch

      - name: Checkout base commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          clean: false

      - name: Benchmark baseline and generate comparison message
        env:
          RESULTS_NAME: ${{ env.BASE_REF_SHA }}
        run: |
          cd benchmarks

          ./bench.sh run tpch
          
          # Temporary workaround, until `RESULTS_NAME` var lands into main
          mv -f results/HEAD results/${{ env.BASE_REF_SHA }}
          
          echo ${{ github.event.pull_request.number }} > pr
          
          pip3 install rich
          cat > message.md <<EOF
          # Benchmark results
          
          <details>
          <summary>Benchmarks comparing ${{ github.event.pull_request.base.sha }} and ${{ github.sha }}</summary>

          \`\`\`
          $(./bench.sh compare ${{ env.BASE_REF_SHA }} ${{ env.HEAD_REF_SHA }})
          \`\`\`

          </details>
          EOF
          
          cat message.md

      - name: Upload benchmark comparison message
        uses: actions/upload-artifact@v4
        with:
          name: message
          path: benchmarks/message.md

      - name: Upload PR number
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: benchmarks/pr

  comment:
    name: Post benchmarks comment
    runs-on: ubuntu-latest
    needs: [ benchmark ]
    steps:
      - name: Download comment message
        uses: actions/download-artifact@v4
        with:
          name: message

      - name: Download pr number
        uses: actions/download-artifact@v4
        with:
          name: pr

      - name: Print message and pr number
        run: |
          cat pr
          echo "PR_NUMBER=$(cat pr)" >> "$GITHUB_ENV"
          cat message.md

      - name: Post a comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('message.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: process.env.PR_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: content,
            })
