name: Benchmarks

on:
  issue_comment:

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/benchmark')
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout PR changes
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: Setup data and generate unique result names
        run: |
          cd benchmarks
          mkdir data
          
          # Setup the TPC-H data set with a scale factor of 10
          ./bench.sh data tpch
          
          # Generate a unique-ish identifiers for the results
          echo "HEAD_REF_SHA=pr-${{ github.event.issue.number }}" >> "$GITHUB_ENV" 
          
          short_sha=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "BASE_REF_SHA=main-$short_sha" >> "$GITHUB_ENV"

      - name: Benchmark PR changes
        env:
          RESULTS_NAME: ${{ env.HEAD_REF_SHA }}
        run: |
          cd benchmarks

          ./bench.sh run tpch

      - name: Checkout base commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          clean: false

      - name: Benchmark baseline and generate comparison message
        env:
          RESULTS_NAME: ${{ env.BASE_REF_SHA }}
        run: |
          cd benchmarks

          ./bench.sh run tpch
          
          # Temporary workaround, until `RESULTS_NAME` var lands into main
          mv -f results/HEAD results/${{ env.BASE_REF_SHA }}
          
          echo ${{ github.event.issue.number }} > pr
          
          pip3 install rich
          cat > message.md <<EOF
          # Benchmark results
          
          <details>
          <summary>Benchmarks comparing ${{ github.sha }} and PR ${{ github.event.issue.number }}</summary>

          \`\`\`
          $(./bench.sh compare ${{ env.BASE_REF_SHA }} ${{ env.HEAD_REF_SHA }})
          \`\`\`

          </details>
          EOF
          
          cat message.md

      - name: Upload benchmark comparison message
        uses: actions/upload-artifact@v4
        with:
          name: message
          path: benchmarks/message.md

      - name: Upload PR number
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: benchmarks/pr
