# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Rust

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/pull_request_template.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/pull_request_template.md"
  # manual trigger
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:

  # test the crate
  linux-test:
    name: cargo test (amd64)
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-builder
        with:
          rust-version: stable
      - name: Print environment
        run: set
      - name: Check disk space in $GITHUB_WORKSPACE
        run: du -s -h $GITHUB_WORKSPACE || true
      - name: Check disk space in $GITHUB_WORKSPACE/*
        run: du -s -h $GITHUB_WORKSPACE/* || true
      - name: Check disk space on /
        run: du -s -h / || true
      - name: Check disk space on /*
        run: du -s -h /* || true
      - name: Check disk space on /lib/*
        run: du -s -h /lib/* || true
      - name: Check disk space on /usr/*
        run: du -s -h /usr/* || true
      - name: Check disk space on /usr/local/*
        run: du -s -h /usr/local/* || true
      - name: Run tests (excluding doctests), ignoring failures
        run: cargo test --lib --tests --bins --features avro,json,dictionary_expressions --norun || true
      - name: Check disk space in $GITHUB_WORKSPACE
        run: du -s -h $GITHUB_WORKSPACE || true
      - name: Check disk space in $GITHUB_WORKSPACE/*
        run: du -s -h $GITHUB_WORKSPACE/* || true
      - name: Check disk space in $GITHUB_WORKSPACE/target
        run: du -s -h $GITHUB_WORKSPACE/target/* || true
      - name: Check disk space in $GITHUB_WORKSPACE/target/debug
        run: du -s -h $GITHUB_WORKSPACE/target/debug/* || true
      - name: Check disk space on /
        run: du -s -h / || true
      - name: List all files after to run
        run: find / || true
      - name: Verify Working Directory Clean
        run: git diff --exit-code
